name: "CMake Action"
author: "Zhe Deng"
description: "CMake/CTest/Ninja build in release mode, test, and install."
outputs:
    install-directory:
        description: "Directory containing the install."
        value: ${{steps.CMake.outputs.install-directory}}
runs:
    using: "composite"
    steps:
        - name: Install Ninja
          run: pip install -y ninja
        - name: CMake
          env:
            CMAKE_BUILD_DIRECTORY: ${{ github.workspace }}/build
            CMAKE_INSTALL_DIRECTORY: ${{ github.workspace }}/build/install
          run: |
            mkdir ${{env.CMAKE_BUILD_DIRECTORY}} && cd ${{env.CMAKE_BUILD_DIRECTORY}}
            cmake -DCMAKE_INSTALL_PREFIX=${{env.CMAKE_INSTALL_DIRECTORY}} -DCMAKE_BUILD_TYPE=Release -G Ninja ..
            cmake --build .
            ctest
            cmake --install . --strip
            echo "install-directory=${{env.CMAKE_INSTALL_DIRECTORY}}" >> $GITHUB_OUTPUT
branding:
    icon: "settings"
    color: "green"
