name: 'CMake Install'
author: 'Zhe Deng'
description: 'CMake/CTest release mode build, test, and install.'
outputs:
  install-directory:
    description: 'Directory containing the install.'
    value: ${{steps.cmake.outputs.install-directory}}
runs:
  using: 'composite'
  steps:
    - name: CMake
      id: cmake
      shell: bash
      env:
        #CMAKE_SOURCE_DIRECTORY: ${{github.workspace}} TODO parametrize
        CMAKE_BUILD_DIR: '${{github.workspace}}/build'
        CMAKE_INSTALL_DIR: '${{github.workspace}}/build/install'
      run: |
        cmake -B ${{env.CMAKE_BUILD_DIR}} -DCMAKE_INSTALL_PREFIX=${{env.CMAKE_INSTALL_DIR}} -DCMAKE_BUILD_TYPE=Release '${{github.workspace}}'
        cmake --build ${{env.CMAKE_BUILD_DIR}}
        ctest --test-dir ${{env.CMAKE_BUILD_DIR}}
        cmake --install ${{env.CMAKE_BUILD_DIR}} --strip
        echo "install-directory=${{env.CMAKE_INSTALL_DIR}}" >> $GITHUB_OUTPUT
branding:
  icon: 'settings'
  color: 'green'
