name: Main

on:
  push:
    branches: ['master']
    tags: ['*']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Test
        run: cmake -P ${{github.workspace}}/template.cmake
        working-directory: test
    #   - name: Test a release version
    #     run: cmake -P ${{github.workspace}}/cmake/wrun.cmake
    #     working-directory: test
  release:
    if: ${{github.ref_type == 'tag'}}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Release Tag
        run: gh release create ${{github.ref_name}} -n ${{github.ref_name}} template.cmake
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
