name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: CTest
        env:
          TEST: 'TEST'
        run: |
          git clone --depth 1 -b master https://github.com/thezhe/template.cmake.git
          cd template.cmake
          cmake -B build && ctest -C Release --output-on-failure --test-dir build
  release:
    if: ${{github.ref_type == 'tag'}}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Release Tag
        run: gh release create ${{github.ref_name}} -n ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
