name: Test

on:
  push:
    branches: ['master']
    tags: ['*']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Test script.ps1
        run: ../script.ps1
        working-directory: test
      - name: Test script.ps1 release
        run: (Invoke-WebRequest 'https://github.com/thezhe/script-template/releases/download/v1.0.1/script.ps1' || wget 'https://github.com/thezhe/script-template/releases/download/v1.0.1/script.ps1' -OutFile script.ps1) && (chmod +x ./script.ps1 || 'true') && ./script.ps1 && rm script.ps1
        working-directory: test
  release:
    if: ${{github.ref_type == 'tag'}}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Release Tag
        run: gh release create ${{github.ref_name}} -n ${{github.ref_name}} *.ps1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
